# Unite

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'osyo-manga/unite-filters-collection'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'unite-filters-collection']
hook_add = 'source ~/.vim/rc/plugins/unite.vim'
hook_source = 'source ~/.vim/rc/plugins/unite_on_source.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-help'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-ssh'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'ryotakato/unite-outline-objc'
depends = ['unite.vim', 'Shougo/unite-outline']
on_ft = 'objc'

[[plugins]]
repo = 'hewes/unite-gtags'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-build'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-ref'
depends = 'unite.vim'
on_source = 'unite.vim'
hook_add = '''
    autocmd Portown FileType ref-webdict nnoremap <buffer> q <C-W>c
'''
hook_source = '''
    let g:ref_source_webdict_sites = {
                \   "wikipedia:ja": {
                \     "url": "http://ja.wikipedia.org/wiki/%s",
                \     "keyword_encoding": "utf-8",
                \     "cache": 1,
                \   },
                \   "wiktionary": {
                \     "url": "http://ja.wiktionary.org/wiki/%s",
                \     "keyword_encoding": "utf-8",
                \     "cache": 1,
                \   },
                \ }
    function! g:ref_source_webdict_sites.wiktionary.filter(output)
        return join(split(a:output, "\n")[18 :], "\n")
    endfunction

    let g:ref_source_webdict_sites.default = "wiktionary"
'''

[[plugins]]
repo = 'Shougo/junkfile.vim'
depends = 'unite.vim'
on_source = 'unite.vim'
