# Unite

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'osyo-manga/unite-filters-collection'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'unite-filters-collection']
hook_add = 'source ~/.vim/rc/plugins/unite.vim'
hook_source = 'source ~/.vim/rc/plugins/unite_on_source.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
hook_add = 'source ~/.vim/rc/plugins/denite.vim'
hook_source = 'source ~/.vim/rc/plugins/denite_on_source.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/junkfile.vim'
depends = 'unite.vim'
on_source = 'unite.vim'

# Language

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp', 'objcpp']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_path = '\.md$'
hook_source = '''
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_conceal_code_blocks = 0
    let g:vim_markdown_folding_level = 6
'''

[[plugins]]
repo = 'tfnico/vim-gradle'
on_path = '\.gradle$'

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_add = '''
    let g:haskell_conceal = 0
'''

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']
if = 'executable("ghc-mod")'
hook_add = '''
    autocmd BufWritePost *.hs GhcModCheckAndLintAsync
'''

[[plugins]]
repo = 'honza/dockerfile.vim'
on_path = 'Dockerfile$'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_source = '''
    let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'asciidoc/vim-asciidoc'
on_path = '\.\%(adoc\|asciidoc\)$'
on_ft = 'asciidoc'

# Completions

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'context_filetype.vim'
on_i = 1
on_ft = 'snippet'
on_source = 'unite.vim'
hook_add = 'source ~/.vim/rc/plugins/neosnippet.vim'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
if = 'executable("ghc-mod")'
hook_add = '''
    let g:necoghc_enable_detailed_browse = 1
'''

# Others

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'
on_path = '.*'

[[plugins]]
repo = 'cohama/agit.vim'
on_cmd = ['Agit', 'AgitFile', 'AgitGit', 'AgitDiff']
hook_add = '''
    let g:agit_enable_auto_show_commit = 0
    let g:agit_enable_auto_refresh = 0
    let g:agit_max_log_lines = 120

    nnoremap <SID>[agit] <Nop>
    nmap <SID>[git]v <SID>[agit]
    nnoremap <silent> <SID>[agit]v :<C-U>Agit<CR>
    nnoremap <silent> <SID>[agit]f :<C-U>AgitFile<CR>

    autocmd Portown filetype agit nnoremap <buffer> git :<C-U>AgitGit 
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_source = '''
    cmap <C-h> <BS>

    " for m4
    call lexima#add_rule({
                \   "char": "`",
                \   "input": "`",
                \   "input_after": "'",
                \   "filetype": "m4",
                \ })
    call lexima#add_rule({
                \   "char": "'",
                \   "at": "`\%#'",
                \   "leave": 1,
                \   "filetype": "m4",
                \ })
    call lexima#add_rule({
                \   "char": "<BS>",
                \   "at": "`\%#'",
                \   "delete": 1,
                \   "filetype": "m4",
                \ })
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
hook_source = '''
    let g:quickrun_config = {}

    let g:quickrun_config._ = {
                \       "outputter": "error",
                \       "outputter/error/success": "buffer",
                \       "outputter/error/error": "quickfix",
                \   }

    if has('job')
        let g:quickrun_config._.runner = 'job'
    else
        let g:quickrun_config._.runner = 'vimproc'
        let g:quickrun_config._['runner/vimproc/updatetime'] = 60
    endif

    let g:quickrun_config.haskell = {
                \       "command": "runghc",
                \   }
    if IsWindows()
        let g:quickrun_config.haskell["hook/output_encode/encoding"] = "cp932"
    endif

    let g:quickrun_config.ruby = {
                \       "command": "ruby",
                \   }
'''

[[plugins]]
repo = 'thinca/vim-template'
on_path = '.*'

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = ['Gina', 'Gina!', 'Gina!!']
hook_add = '''
    nnoremap <SID>[git] <Nop>
    nmap <Space>g <SID>[git]
    nnoremap <SID>[git]d :<C-U>Gina patch<CR>
    nnoremap <SID>[git]s :<C-U>Gina status<CR>
    nnoremap <SID>[git]b :<C-U>Gina blame<CR>
    nnoremap <SID>[git]r :<C-U>Gina branch --all<CR>
'''
