" .gvimrc

" -------------------------------------------------------------
" ウィンドウ設定 {{{

" 起動時にウィンドウ最大化
if IsWindows()
  autocmd Portown GUIEnter * simalt ~x
elseif has( 'gui_macvim' )
  set lines=999 columns=9999
else
  autocmd Portown GUIEnter * winpos 0 0
  set lines=59
  set columns=239
endif

set guioptions&

" ツールバーとメニューバーを消す
set guioptions-=T
set guioptions-=m

" スクロールバーを消す
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" テキストベースの tabline を使用する
set guioptions-=e

" タイトルを固定する
set titlestring=gVim

" }}}
" -------------------------------------------------------------

" -------------------------------------------------------------
" フォント設定 {{{

if IsWindows()
  set guifont=Ricty\ for\ Powerline:h12:cSHIFTJIS

  if exists( '&rop' )
    " DirectWrite の設定
    "   pixelGeometry: RGB
    "   renderingMode: NATURAL_SYMMETRIC
    "   textAntialiasMode: CLEARTYPE
    set rop=type:directx,gamma:1.7,contrast:1.0,level:0.8,geom:1,renmode:5,taamode:1
  endif
elseif has('gui_gtk2')
  set guifont=Ricty\ 12
else
  set guifont=Ricty\ for\ Powerline:h16
endif

" }}}
" -------------------------------------------------------------

" -------------------------------------------------------------
" 日本語入力設定 {{{

" 日本語入力オン時のカーソル色を変更する
highlight CursorIM guibg=Red

set iminsert=0
set imsearch=0

" }}}
" -------------------------------------------------------------

" -------------------------------------------------------------
" マウス設定 {{{

set mouse=
set nomousefocus
set mousehide

" }}}
" -------------------------------------------------------------
