# Others

[[plugins]]
repository = 'vim-scripts/sudo.vim.git'

[[plugins]]
repository = 'ujihisa/shadow.vim'

[[plugins]]
repository = 'itchyny/landscape.vim'

[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'thinca/vim-localrc'

[[plugins]]
repository = 'tpope/vim-repeat'

[[plugins]]
repository = 'fuenor/qfixgrep'

[[plugins]]
repository = 'fuenor/qfixhowm'
